services:
  api-gateway:
    ports:
      - "8080:8000"
    environment:
      LOG_LEVEL: INFO

  writer-service:
    restart: unless-stopped

  inventory-service:
     restart: unless-stopped

  notification-service:
     restart: unless-stopped

  auth-service:
    ports:
      - "8081:8000"
    environment:
      LOG_LEVEL: INFO
    restart: unless-stopped